### ISSUE TITLE
[BUG] Pincode and phone number validation

### ISSUE THREAD

**Issue by jofinjo** [koodorukkam/noah#1]
In chrome and firefox, phone number field and pincode field accept more than 10   digits and 6 digits respectively.   Clicking on donate button, throwing the below error message "Contact number has to be a   10-digit mobile number & Invalid PIN code   " .      In Edge, its limited to 10 and 6 digits while entering itself which is proper

**Comment by syam1123** [comment]
working on it

**Comment by syam1123** [comment]
What if the user is entering landline number? Should we validate that case?

**Comment by syam1123** [comment]
added validation for landline as well. But the land number can be 11 digits. The backend is responding with an error
