### ISSUE TITLE
Partner section edit 

### ISSUE THREAD

**Issue by jofinjo** [koodorukkam/noah#36]
Add partner logo to the list in the website. 

1. GTech - logo is in the website. Please link to http://gtechindia.org/
2. NASSCOM - Logo is there already, link to https://www.nasscom.in/
4. PrathiDhwani - Add the below logo and link to http://www.prathidhwani.org/

![prathidhwanilogo](https://user-images.githubusercontent.com/42801729/44942608-398c4980-add3-11e8-9682-1e50fa7e46a8.png)

**Comment by shaminmeerankutty** [comment]
Working on it.

**Comment by shaminmeerankutty** [comment]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/8272719/44943176-a60d4580-addf-11e8-8b21-6557ae4e7bf3.png">
Done

**Comment by shaminmeerankutty** [comment]
<img width="1680" alt="screen shot 2018-09-01 at 5 54 58 pm" src="https://user-images.githubusercontent.com/8272719/44945997-27310080-ae11-11e8-8bf3-4f83a6f1db8c.png">

**Comment by koodorukkam** [comment]
Closed since this is in force.
